### ISSUE TITLE
Sort function in getMedian() isn't sorting on value, but on text

### ISSUE THREAD

**Issue by jdhines** [planetoftheweb/CodeClinicJS#1]
Working through your Lynda.com course now, so thanks for that!

I noticed when testing some different sample data though: `var test = [1,2,3,10,33];` that it will return 2 instead of 3 as expected since the sorted array when doing `myArray.sort()` is `[1,10,2,3,33]`. Upon reading up on Array.sort(), I found that the parameter should be the sort function, not the array you're sorting, so to correctly sort on value, the `sorted` variable should be more like this I think:

```
var sorted = myArray.sort(function(a, b) {
    return a > b;
});
```

**Comment by planetoftheweb** [comment]
Good catch. I've updated the 01_09 branch with this change.
